In [23]:
import pandas as pd 
df = pd.read_csv('Booking_ola.csv')

In [24]:
df.head(10)

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT (mins),Avg CTAT (mins),Cancelled Rides by Customer,Reason for Cancelling by Customer,Cancelled Rides by Driver,Reason for Cancelling by Driver,Incomplete Rides,Incomplete Rides Reason,Booking Value (INR),Ride Distance (km),Driver Rating,Customer Rating
0,12-05-2024,16:07:10,CNR2867825,Incomplete Ride,CUST27140,Prime SUV,Nigdi,Ambegaon,NaN,NaN,0,NaN,0,NaN,1,Vehicle Breakdown,NaN,NaN,NaN,NaN
1,29-05-2024,15:40:27,CNR1419610,Success,CUST60374,Auto,Sus,Pimple Saudagar,2.95,4.57,0,NaN,0,NaN,0,NaN,124.59,4.02,3.8,3.2
2,23-05-2024,12:53:12,CNR5614226,Success,CUST94944,Prime SUV,Balewadi,Sangvi,4.43,5.58,0,NaN,0,NaN,0,NaN,422.69,4.79,3.9,4.0
3,19-05-2024,15:09:51,CNR5108603,Success,CUST78602,Mini,Kothrud,Pimpri,9.81,5.40,0,NaN,0,NaN,0,NaN,435.06,19.82,3.7,4.6
4,05-05-2024,12:10:21,CNR4744854,Other,CUST24131,Prime Sedan,Kothrud,Kharadi,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5,05-05-2024,18:17:49,CNR3341057,Cancelled by Driver,CUST24351,Auto,Vishrantwadi,Katraj,NaN,NaN,0,NaN,1,Customer related issue,0,NaN,NaN,NaN,NaN,NaN
6,02-05-2024,20:31:57,CNR2719583,Other,CUST92181,eBike,Dhankawadi,Sinhagad Road,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
7,27-05-2024,19:15:06,CNR2458591,Success,CUST79760,Prime Sedan,Katraj,Kondhwa,6.93,4.49,0,NaN,0,NaN,0,NaN,522.70,26.50,3.8,4.0
8,19-05-2024,12:56:44,CNR8078673,Success,CUST34028,eBike,Wakad,Viman Nagar,13.56,2.64,0,NaN,0,NaN,0,NaN,626.07,28.46,3.2,4.1
9,22-05-2024,15:19:29,CNR1533224,Success,CUST95653,Bike,Pisoli,Deccan Gymkhana,6.97,11.90,0,NaN,0,NaN,0,NaN,538.78,29.92,3.9,4.4

In [34]:
# Renaming columns according to snake casing for better readability and documentation

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [35]:
df.columns

Index(['date', 'time', 'booking_id', 'booking_status', 'customer_id',
       'vehicle_type', 'pickup_location', 'drop_location', 'avg_vtat_(mins)',
       'avg_ctat_(mins)', 'cancelled_rides_by_customer',
       'reason_for_cancelling_by_customer', 'cancelled_rides_by_driver',
       'reason_for_cancelling_by_driver', 'incomplete_rides',
       'incomplete_rides_reason', 'booking_value_(inr)', 'ride_distance_(km)',
       'driver_rating', 'customer_rating'],
      dtype='str')

In [26]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\patil\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [36]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
username = "postgres"
password = "postgres123"
host = "localhost"
port = "5432"
database = "Ola"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "bookings"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'")

Data successfully loaded into table 'bookings' in database 'Ola'

In [33]:
len(df)

100000

In [28]:
df.isna().sum()

Date                                     0
Time                                     0
Booking ID                               0
Booking Status                           0
Customer ID                              0
Vehicle Type                             0
Pickup Location                          0
Drop Location                            0
Avg VTAT (mins)                      37906
Avg CTAT (mins)                      37906
Cancelled Rides by Customer              0
Reason for Cancelling by Customer    93128
Cancelled Rides by Driver                0
Reason for Cancelling by Driver      82013
Incomplete Rides                         0
Incomplete Rides Reason              94032
Booking Value (INR)                  37906
Ride Distance (km)                   37906
Driver Rating                        37906
Customer Rating                      37906
dtype: int64

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               100000 non-null  str
 1   Time                               100000 non-null  str
 2   Booking ID                         100000 non-null  str
 3   Booking Status                     100000 non-null  str
 4   Customer ID                        100000 non-null  str
 5   Vehicle Type                       100000 non-null  str
 6   Pickup Location                    100000 non-null  str
 7   Drop Location                      100000 non-null  str
 8   Avg VTAT (mins)                    62094 non-null   float64
 9   Avg CTAT (mins)                    62094 non-null   float64
 10  Cancelled Rides by Customer        100000 non-null  int64
 11  Reason for Cancelling by Customer  6872 non-null    str
 12  Cancelled Rides by Driver          100000 non-null  int64
 13  Reason for Cancelling by Driver    17987 non-null   str
 14  Incomplete Rides                   100000 non-null  int64
 15  Incomplete Rides Reason            5968 non-null    str
 16  Booking Value (INR)                62094 non-null   float64
 17  Ride Distance (km)                 62094 non-null   float64
 18  Driver Rating                      62094 non-null   float64
 19  Customer Rating                    62094 non-null   float64
dtypes: float64(6), int64(3), str(11)
memory usage: 15.3 MB

In [30]:

df.describe(include='all')

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT (mins),Avg CTAT (mins),Cancelled Rides by Customer,Reason for Cancelling by Customer,Cancelled Rides by Driver,Reason for Cancelling by Driver,Incomplete Rides,Incomplete Rides Reason,Booking Value (INR),Ride Distance (km),Driver Rating,Customer Rating
count,100000,100000,100000,100000,100000,100000,100000,100000,62094.000000,62094.000000,100000.000000,6872,100000.000000,17987,100000.000000,5968,62094.000000,62094.000000,62094.000000,62094.000000
unique,31,52320,99456,5,60288,7,50,50,NaN,NaN,NaN,5,NaN,4,NaN,3,NaN,NaN,NaN,NaN
top,11-05-2024,07:00:17,CNR1482732,Success,CUST10259,Auto,Pisoli,Wanowrie,NaN,NaN,NaN,Driver is not moving towards pickup location,NaN,The customer was coughing/sick,NaN,Vehicle Breakdown,NaN,NaN,NaN,NaN
freq,5279,11,3,62094,7,25077,2096,2108,NaN,NaN,NaN,1604,NaN,4535,NaN,2022,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.989885,6.497442,0.068720,NaN,0.179870,NaN,0.059680,NaN,522.054280,18.252231,4.001681,3.998043
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.036999,3.171332,0.252979,NaN,0.384081,NaN,0.236894,NaN,391.571424,9.699830,0.578645,0.579591
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,0.000000,NaN,0.000000,NaN,0.000000,NaN,50.010000,1.500000,3.000000,3.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.500000,3.760000,0.000000,NaN,0.000000,NaN,0.000000,NaN,247.085000,9.850000,3.500000,3.500000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.990000,6.490000,0.000000,NaN,0.000000,NaN,0.000000,NaN,435.740000,18.200000,4.000000,4.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.470000,9.250000,0.000000,NaN,0.000000,NaN,0.000000,NaN,698.275000,26.710000,4.500000,4.500000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.000000,12.000000,1.000000,NaN,1.000000,NaN,1.000000,NaN,4132.260000,35.000000,5.000000,5.000000

In [31]:
# Just verify the logic is correct
print(df['Booking Status'].value_counts())

# Success rows should match non-null VTAT rows
success_count = df[df['Booking Status'] == 'Success'].shape[0]
non_null_vtat = df['Avg VTAT (mins)'].notna().sum()

print(f"Success rides: {success_count}")
print(f"Non-null VTAT: {non_null_vtat}")
# Both should be equal ✅

Booking Status
Success                  62094
Cancelled by Driver      17987
Other                     7079
Cancelled by Customer     6872
Incomplete Ride           5968
Name: count, dtype: int64
Success rides: 62094
Non-null VTAT: 62094